http://export.arxiv.org/oai2?verb=ListRecords&from=2009-09-01&until=2010-08-31&metadataPrefix=arXiv&set=math
fetching up to  1000 records...
fetching up to  2000 records...
Got 503. Retrying after 30 seconds.
fetching up to  3000 records...
fetching up to  4000 records...
Got 503. Retrying after 30 seconds.
fetching up to  5000 records...
fetching up to  6000 records...
Got 503. Retrying after 30 seconds.
fetching up to  7000 records...
fetching up to  8000 records...
Got 503. Retrying after 30 seconds.
fetching up to  9000 records...
fetching up to  10000 records...
Got 503. Retrying after 30 seconds.
fetching up to  11000 records...
fetching up to  12000 records...
Got 503. Retrying after 30 seconds.
fetching up to  13000 records...
fetching up to  14000 records...
Got 503. Retrying after 30 seconds.
fetching up to  15000 records...
fetching up to  16000 records...
Got 503. Retrying after 30 seconds.
fetching up to  17000 records...
fetching up to  18000 records...
Got 503. Retrying after 30 seconds.
fetching up to  19000 records...
fetching up to  20000 records...
Got 503. Retrying after 30 seconds.
fetching up to  21000 records...
fetching up to  22000 records...
Got 503. Retrying after 30 seconds.
fetching up to  23000 records...
fetching up to  24000 records...
Got 503. Retrying after 30 seconds.
fetching up to  25000 records...
Traceback (most recent call last):
  File "scrape8.py", line 20, in <module>
    output = scraper.scrape()
  File "/home/taduyan/cse691/arxivscraper-master/arxivscraper/arxivscraper.py", line 143, in scrape
    meta = record.find(OAI + 'metadata').find(ARXIV + 'arXiv')
AttributeError: 'NoneType' object has no attribute 'find'
